/**
 * by CntChen 2016.07.22
 */

export const SET_LOGIN_STATE_TO_HAS_LOGIN = 'SET_LOGIN_STATE_TO_HAS_LOGIN';
export const SET_LOGIN_STATE_TO_HAS_LOGOUT = 'SET_LOGIN_STATE_TO_HAS_LOGOUT';
export const SET_LOGIN_STATE_TO_REGISTER = 'SET_LOGIN_STATE_TO_REGISTER';

export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const REQUEST_ORDERS_FAILED = 'REQUEST_ORDERS_FAILED';
export const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';